name: Build & Push Docker Image to GHCR

on:
  push:
    branches: [main,master]
    tags: ["v*"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed for GHCR push
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID_LOWER=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')
          docker build -t $IMAGE_ID_LOWER:latest .

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID_LOWER=$(echo "$IMAGE_ID" | tr '[A-Z]' '[a-z]')
          docker push $IMAGE_ID_LOWER:latest